-- Use whole_food_market;
-- describe wfm_customers ;
-- describe wfm_return ;
-- describe wfm_orders ;


-- 1 "find out which category is performing better in terms of profit than the others so that business can find ways to improve." 

-- select Category , Sum(Profit) from wfm_orders group by Category 
-- order by Sum(Profit) DESC;
-- "Technology was highest profit making category"

-- 2. "While going through the data set you found out that the State column in the Orders table also contains Union territories and found a mistake.
-- You found that for Chandigarh the city is marked as Delhi. You pointed out this mistake to database manager and he asks you to update the table"


-- Update wfm_orders set city = 'chandigarh' Where state = 'chandigarh';
-- Select * from wfm_orders where state = 'Chandigarh' ;

-- 3. "As a next step, you want to know how much company profit has been generated by the company so far".
-- select sum(Profit) from wfm_orders;

-- "4 You saw that the company has made good profits so far. You are required to report which order had the highest profit so far."
select `Order ID`, `Product Name`, Profit from wfm_orders
order by Profit Desc ;

-- "5 Your manager wants to know the Product with highest loss. Write the Product_Name of such product."
select `Product Name`,Profit from wfm_orders
order by profit LIMIT 1;

-- "6. you also want to report orders where there was loss."
select `Order ID`, `Product Name`, Profit from wfm_orders
where profit < 0
order by profit ;

-- "7. Now you know all the orders where there was a loss. You are curious to know why the company made a loss on those items. You see that discounts are also given on some items."
select `Order ID`, `Product Name`, Profit, Discount from wfm_orders
where Profit < 0 
order by Discount desc;

-- Note : highest loss making item was not given highest discount so discount is not the reason for loss 

-- "8. Now we want to know if there are particular states which are making losses. Write a query to get the State and sum of profit for each state."
select state as STATE, sum(Profit) AS `TOTAL PROFIT` from wfm_orders
group by state order by sum(Profit) Desc;

-- "9. Now you want to go further and list categories in each state and see their profit. This will help analyze how various categories are performing in each state. "
select state,category,Sum(Profit) from wfm_orders
group by state,category;

-- "10. Creating new table of managers who are leading different categories"
CREATE Table MANAGERS( 
Segment VARCHAR(100) primary key , 
Segment_Managers VARCHAR(100));

INSERT INTO MANAGERS(Segment,Segment_Managers) values 
('Consumer','Gagan Singh'),
('Corporate','Simran Rana'),
('Home Office','Kush Arora');

-- check the table created
select * from managers;

-- "11. Now you have a table in the database named Manager. You are required to get the total profit and total orders for each segment."
select Segment,count(`Order Id`) AS Total_Order,Sum(Profit)
from wfm_orders Group by Segment;

-- Note as Consumer segment has highest profit lead by manager Gagan Singh.

-- "12.Since you want to help the segment managers get fair evaluation and your manager has asked you to get the covid effect on the sales. Write the query to get sum of sales, sum of profit for the year 2020. "
select SUM(Sales) AS Total_Sales,SUM(Profit) AS Total_Profit
from wfm_orders where `Order Date` like "%20";


-- "13. Now your manager wants you to remove 2020 from the total sales and profit and present the result. Write a query to get the sum of sales of each segment and their respective segment manager for all years except 2020."
 select SUM(wfm_orders.Sales) AS Total_Sales, managers.Segment_Managers from wfm_orders
 LEFT JOIN managers
 ON wfm_orders.segment = managers.segment
 where wfm_orders.`Order Date` NOT LIKE "%20"
 group by wfm_orders.segment;
 
 -- "14. You have helped your manager make the right decision in performance evaluation of segment managers. As for the next task, he wants you to help him do analysis on the customer level."
 -- "Write a query to get Customer ID and sum of profit for each. The result should be such that you are easily able to find the highest profit customer."
 
 select `Customer Id`,SUM(profit) AS Total_Profit
 From wfm_orders Group by `Customer Id`
 Order By SUM(profit) DESC;
 
 -- Customer Id with highest profit TC-20980

-- "15 Write a query to find the customer details having the highest Profit. The result should be such that you are easily able to find the highest profitable customer."
-- "The query should have columns : Customer_ID, Customer_Name_, sum of Sales, sum of Profit, count of Order_ID."

select C.`Customer ID`,C.`Customer Name`, Sum(O.Sales),Sum(O.Profit),count(O.`Order ID`) from wfm_customers as C
Join wfm_orders as O
ON C.`Customer ID` = O.`customer Id`
group by C.`Customer ID`, C.`Customer Name`
order by Sum(O.Profit) DESC;
 
 

















